language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  repo: NiRongFei/blog
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  skip-cleanup: true
  on:
    branch: master
